"""expense series

Revision ID: c627684d26a5
Revises: f3786c655452
Create Date: 2026-09-03 01:45:28.280883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c627684d26a5'
down_revision: Union[str, Sequence[str], None] = 'f3786c655452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('series_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('series_total', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expense_series_id'), ['series_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_series_id'))
        batch_op.drop_column('series_total')
        batch_op.drop_column('series_index')
        batch_op.drop_column('series_id')

    # ### end Alembic commands ###
